import createClient, { type Middleware } from 'openapi-fetch';
import type { paths } from './schema'; // generated by openapi-typescript
import { API_KEY, BASE_URL } from '../config/api-config';
import { localStorageKeys } from '../config/localstorage-keys';

let refreshPromise: Promise<void> | null = null;

function makeRefreshToken() {
  if (!refreshPromise) {
    refreshPromise = (async (): Promise<void> => {
      const refreshToken = localStorage.getItem(localStorageKeys.refreshToken);
      if (!refreshToken) {
        throw new Error('no refresh token');
      }

      const res = await fetch(`${BASE_URL}auth/refresh`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'api-key': API_KEY,
        },
        body: JSON.stringify({ refreshToken }),
      });

      if (!res.ok) {
        localStorage.removeItem(localStorageKeys.accessToken);
        localStorage.removeItem(localStorageKeys.refreshToken);
        throw new Error(`Error: refresh token failed`);
      }

      const data = await res.json();
      localStorage.setItem(localStorageKeys.accessToken, data.accessToken);
      localStorage.setItem(localStorageKeys.refreshToken, data.refreshToken);
    })();
    refreshPromise.finally(() => {
      refreshPromise = null;
    });

    return refreshPromise;
  }
}

const authMiddleware: Middleware = {
  onRequest({ request }) {
    const accessToken = localStorage.getItem(localStorageKeys.accessToken);
    if (accessToken) {
      request.headers.set('Authorization', `Bearer ${accessToken}`);
    }

    // @ts-expect-error hot fix
    request._retryRequest = request.clone();

    return request;
  },
  async onResponse({ request, response }) {
    if (response.ok) return response;
    if (!response.ok && response.status !== 401) {
      const errorBody = await response.json();
      throw errorBody;
    }
    try {
      await makeRefreshToken();
      // @ts-expect-error ignore it
      const originalRequest: Request = request._retryRequest;
      const retryRequest = new Request(originalRequest, { headers: new Headers(originalRequest.headers) });
      retryRequest.headers.set('Authorization', `Bearer ${localStorage.getItem(localStorageKeys.accessToken)}`);
      return fetch(retryRequest);
    } catch {
      return response;
    }
  },
};

export const client = createClient<paths>({
  baseUrl: BASE_URL,
  headers: { 'api-key': API_KEY },
});

client.use(authMiddleware);
